//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archives
    {
        public int Id { get; set; }
        public int Number_Card { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Passport { get; set; }
        public string Adress { get; set; }
        public string Phone_number { get; set; }
        public System.DateTime Date_birth { get; set; }
        public int Id_Therapist { get; set; }
        public System.DateTime Date_move { get; set; }
    
        public virtual Therapists Therapists { get; set; }
    }
}
