//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Registration_patientsEntities : DbContext
    {
        public Registration_patientsEntities()
            : base("name=Registration_patientsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analyzes> Analyzes { get; set; }
        public virtual DbSet<Archives> Archives { get; set; }
        public virtual DbSet<Card_Patients> Card_Patients { get; set; }
        public virtual DbSet<Procedures> Procedures { get; set; }
        public virtual DbSet<Ref_Analyzes> Ref_Analyzes { get; set; }
        public virtual DbSet<Ref_Procedures> Ref_Procedures { get; set; }
        public virtual DbSet<Ref_Analyzes> Result_Analyzes { get; set; }
        public virtual DbSet<Sick_leaves> Sick_leaves { get; set; }
        public virtual DbSet<Therapists> Therapists { get; set; }
    }
}
