//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Analyzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Analyzes()
        {
            this.Result_Analyzes = new HashSet<Result_Analyzes>();
        }
    
        public int Id { get; set; }
        public int Id_Patient { get; set; }
        public int Id_Therapist { get; set; }
        public int Id_Analyze { get; set; }
        public System.DateTime Date_analyze { get; set; }
    
        public virtual Analyzes Analyzes { get; set; }
        public virtual Card_Patients Card_Patients { get; set; }
        public virtual Therapists Therapists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result_Analyzes> Result_Analyzes { get; set; }
    }
}
