//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sick_leaves
    {
        public int Id { get; set; }
        public int Id_Patient { get; set; }
        public string PlaceOfWork { get; set; }
        public string Diagnosis { get; set; }
        public bool IsAmbulatory { get; set; }
        public bool IsStationary { get; set; }
        public int Id_Therapist { get; set; }
        public System.DateTime Opening_date { get; set; }
        public System.DateTime Closing_date { get; set; }
    
        public virtual Card_Patients Card_Patients { get; set; }
        public virtual Therapists Therapists { get; set; }
    }
}
